### ISSUE TITLE
Upgrade to newer Docker version

### ISSUE THREAD

**Issue by mitar** [tozd/salt#4]
The issue is that 1.6.2 seems to override `/etc/hosts` so that it is not possible to use [docker-hosts](https://github.com/tozd/docker-hosts).

https://github.com/docker/docker/issues/10316

**Comment by kostko** [comment]
It seems that docker 1.8 already contains all functionality of docker-hosts.

**Comment by mitar** [comment]
Except for: https://github.com/docker/docker/issues/14083#issuecomment-119346611

**Comment by mitar** [comment]
I opened a ticket: https://github.com/docker/docker/issues/17570

**Comment by kostko** [comment]
Is this a critical feature for you? Because we need to upgrade away from 1.5 ASAP as pulls from Docker Hub will no longer be possible with this Docker version.

**Comment by mitar** [comment]
I will just have to be mindful about it when migrating the old server and do a grep in all config files for the whole domain name for our services. Hopefully they are all in files and not in the database.

**Comment by kostko** [comment]
Hm, but it seems that this features has already been reverted due to some issues (docker/docker#17325)?

**Comment by kostko** [comment]
Perhaps we could use [dnsdock](https://github.com/tonistiigi/dnsdock).

**Comment by mitar** [comment]
No, they just removed it from a default network:

> If you need "service discovery", create a network and attach containers to that.

**Comment by mitar** [comment]
I suggested that they make this a configuration option for Docker in 1.9.

**Comment by kostko** [comment]
For now, we will  be using only the hosts-based service discovery provided in Docker 1.8.3. Later, we can check how to do this properly in 1.9+.

**Comment by mitar** [comment]
It seems that in Docker 1.8.3 docker-hosts correctly works again. So I would suggest that for now we continue using docker-hosts then.

**Comment by mitar** [comment]
I restored docker-hosts support with 9d9f680609c75694e8a161056668dc5954b4c2fd.
